config/routes.rb
Rails.application.routes.draw do
  get 'partials/student'
  get 'partials/admin'
  get 'partials/employee'
  get 'configuration/index'
  get 'configuration/settings'
  get 'configuration/advanced'
  get 'configuration/add_weekly_holidays'
  get 'home/index'
  resources :users
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'all', to: 'users#all'
get 'create', to: 'users#create'
get 'index', to: 'users#index'
get 'new' , to: 'users#new'
post '/users/listuser', to: 'users#listuser'
get 'user/profile/:id', to: 'user#profile', as: 'user_profile'


get 'login', to: 'sessions#new', as: 'login'
get 'utilisateurs' , to: 'users#utilisateurs'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'dashboard', to: 'sessions#dashboard'
#get 'new' , to: 'sessions#new'
get 'settings', to: 'configuration#settings'
get 'index', to: 'configuration#index'
get 'advanced', to: 'configuration#advanced'
get 'add_weekly_holidays', to: 'configuration#add_weekly_holidays'
 resources :courses do
    resources :batches
  end
 get 'index' , to: 'courses#index'
 get 'manage_courses', to: 'courses#manage_courses'
  put 'update' , to: 'courses#update'
 get 'edit' , to: 'courses#edit'
 get 'show' , to: 'courses#show'
 get 'new' , to: 'courses#new'
  get 'grouped_batches' , to: 'courses#grouped_batches'
 get 'destroy' , to: 'courses#destroy'
 get 'manage_batches', to: 'courses#manage_batches'
 get 'rechercher_par_filiere' , to: 'courses#rechercher_par_filiere'
 get 'batch_transfers/update_batch', to: 'batch_transfers#update_batch'
get 'grading_levels', to: 'grading_levels#index'
 get 'index', to: 'batch_transfers#index'
 resources :batch_transfers, only: [:index]

  #get 'update' , to: 'courses#update'
 get 'courses/new'
 get 'courses/index'
  #get 'courses/edit'
  #get 'courses/update'
 #get'courses/manage_courses'
 get 'new', to: 'grp_batches#new'
 get 'grp_batches/show_batches/:course_id/:id', to: 'grp_batches#show_batches', as: 'show_batches'
 #delete 'grp_batches/:id', to: 'grp_batches#destroy', as: 'grp_batch'
 delete '/grp_batches/:id', to: 'grp_batches#destroy', as: 'destroy_grp_batch'

 get 'destroy' , to: 'batches#destroy'
  #get 'destroy' , to: 'courses#destroy'
resources :student do
  post 'admission1', on: :collection
end
#resources :manage_courses, only: [:index, :destroy]

  get '/requestdoc_students/index', to: 'requestdoc_students#index'
get 'admission1' , to: 'student#admission1'
get 'profile/:id', to: 'student#profile'
 get 'student/sans_semestre/:id', to: 'student#sans_semestre', as: 'student_sans_semestre'
 get 'student/sans_semestre_sans_rattr/:id', to: 'student#sans_semestre_sans_rattr'
 get 'student/history/:id', to: 'student#history'
 get 'student/student_card/:id', to: 'student#student_card'
 get 'student/gestion_student_card/:id', to: 'student#gestion_student_card'
 
get 'new' , to: 'batches#new'

post 'courses/:course_id/create_batch_group', to: 'courses#create_batch_group', as: 'create_batch_group'


#post '/students', to: 'student#admission1'




 
resources :courses do
  member do
    get 'manage_courses'
    
  end

end
resources :grp_batches do
  collection do
    get 'new/:course_id', to: 'grp_batches#new', as: 'new_grp_batch'
    get 'grouped_batches', to: 'courses#grouped_batches'
  end
end
resources :batch_grps

end

app/controllers/batch_transfers_controller.rb
#FEDENA
#Copyright 2011 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project FEDENA - http://www.projectFEDENA.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class BatchTransfersController < ApplicationController
  before_filter :login_required
  filter_access_to :all

  def index
	@school_fields=SchoolField.find(:all, :order =>"name")
    @batches = Batch.active
  end

  def show
	@students_reus = []
	@students_red = []
    @batch = Batch.find params[:id], :include => [:students],:order => "students.last_name ASC"
	@batch_cible = []
	@batch_red = []
	sf_ids = []
	sf_ids << @batch.school_field_id
    SchoolField.find_all_by_field_root(@batch.school_field_id).each{|sff| sf_ids << sff.id}
    #@batches = Batch.active - @batch.to_a
    sf_ids.each do |sfsf|
    	logger.debug sfsf.to_s+"\n"
    end
    sf_ids.uniq.each do |sfsf|
		if (@batch.course_id == 2)
			logger.debug 2.to_s+' aaaaaaaaa\n'
		@batch_cible << Batch.find(:first, :conditions => "course_id = 3 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
		@batch_red << Batch.find(:first, :conditions => "course_id = 1 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
	        @batch_cible +=  Batch.find(:all,:conditions => "course_id = 3 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
                @batch_red +=  Batch.find(:all,:conditions => "course_id = 1 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
        elsif (@batch.course_id == 4)
        	logger.debug 4.to_s+' aaaaaaaaa\n'
		@batch_cible << Batch.find(:first, :conditions => "course_id = 5 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
		@batch_red << Batch.find(:first, :conditions => "course_id = 3 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
		school_fields = SchoolField.find(:all, :conditions => "field_root = #{sfsf}")
		school_fields.each do |sf|
			bt = Batch.find(:first, :conditions => "course_id = 5 and school_field_id = #{sf.id} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
			@batch_cible << bt unless bt.nil?
		end
                @batch_cible +=  Batch.find(:all,:conditions => "course_id = 5 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
                @batch_red +=  Batch.find(:all,:conditions => "course_id = 3 and school_field_id != #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
	elsif(@batch.course_id == 6)
		logger.debug 6.to_s+' aaaaaaaaa\n'
		@batch_red << Batch.find(:first, :conditions => "course_id = 5 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i + 1).to_s})")
	        @batch_red +=  Batch.find(:all,:conditions => "(course_id = 5 or course_id = 6) and school_field_id = #{sfsf} and (year(start_date) >= #{(@batch.get_batch_year.to_i + 1).to_s})")
        elsif (@batch.course_id == 1)
        	logger.debug 1.to_s+' aaaaaaaaa\n'
		@batch_cible << Batch.find(:first, :conditions => "course_id = 2 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i)+1})")
	        @batch_cible +=  Batch.find(:all,:conditions => "(course_id = 2 or course_id = 3) and school_field_id = #{sfsf} and (year(start_date) >= #{(@batch.get_batch_year.to_i + 1).to_s})")
        elsif (@batch.course_id == 3)
        	logger.debug 3.to_s+' aaaaaaaaa\n'
		@batch_cible << Batch.find(:first, :conditions => "course_id = 4 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i)+1})")
	        @batch_cible += Batch.find(:all, :conditions => "(course_id = 4 or course_id = 5) and school_field_id = #{sfsf} and (year(start_date) >= #{(@batch.get_batch_year.to_i)+1})")
        elsif (@batch.course_id == 5)
        	logger.debug 5.to_s+' aaaaaaaaa\n'
		@batch_cible << Batch.find(:first, :conditions => "course_id = 6 and school_field_id = #{sfsf} and (year(start_date) = #{(@batch.get_batch_year.to_i)+1})")
	        @batch_cible += Batch.find(:all, :conditions => "course_id = 6 and school_field_id = #{sfsf} and (year(start_date) >= #{(@batch.get_batch_year.to_i)+1})")
        end
    end
	@batch_red = @batch_red.uniq.compact
	@batch_cible = @batch_cible.uniq.compact
	# @batch_cible = @batch_cible.reject{|b| b.get_batch_year < @batch.get_batch_year}
	#@batch_cible +=  Batch.all
	#@batch_red +=  Batch.all
	@batch.students.each do |student|
		if(@batch.course_id == 1 or @batch.course_id == 3 or @batch.course_id == 5)
#			ydecision=YearlyDecision.find(:first, :conditions => "student_id = #{student.id} and school_year = #{@batch.get_batch_year.to_s} and batch_ids like '%#{(@batch.id.to_s << ',')}%'")
		  else
			batch_prec = Batch.find(:first, :conditions => "course_id = #{@batch.course_id-1} and school_field_id = #{@batch.school_field_id.to_s} and (year(start_date) = #{@batch.get_batch_year})")
			if(!batch_prec.nil?)
				ydecision=YearlyDecision.find(:first, :conditions => "student_id = #{student.id} and school_year = #{@batch.get_batch_year.to_s} and batch_ids like '%#{(batch_prec.id.to_s << ',' << @batch.id.to_s << ',')}%'")
			end
		  end
		  if(!ydecision.nil?)
		  if( ydecision.decision.to_s != "AnneeReserve" and ydecision.decision.to_s != "Exclu" and ydecision.decision.to_s != "Ajourne" and ydecision.decision.to_s != "Reoriente")
			@students_reus << student
		  else
			@students_red << student
		  end
		  else
		  @students_reus << student
		  end
	end

	@school_fields=SchoolField.find(:all, :order =>"name")

@batch_red = Batch.all
@batch_cicle = Batch.all

=begin
	 elsif(@current_user.employee?)
	 @school_fields=SchoolField.find_by_employee_id(@current_user.employee.id)
	 end
=end
      #@courses=Course.find(:all, :order => "code")
  end

=begin  def transfer
    unless params[:transfer][:students].nil?
      students = Student.find(params[:transfer][:students])
      students.each do |s|
        s.batch_students.create(:batch_id => s.batch.id)
        s.update_attribute(:batch_id, params[:transfer][:to])
        s.update_attribute(:has_paid_fees,0)
      end
    end
    batch = Batch.find(params[:id])
    @stu = Student.find_all_by_batch_id(batch.id)
    if @stu.empty?
      batch.update_attribute :is_active, false
      Subject.find_all_by_batch_id(batch.id).each do |sub|
          sub.employees_subjects.each do |emp_sub|
            emp_sub.delete
          end
      end
    end
    flash[:notice] = "#{t('flash1')}"
    redirect_to :controller => 'batch_transfers'
  end
=end

=begin  def transfer
	@batch_cible = Batch.find params[:transfer][:batch_cible] unless params[:transfer][:batch_red].nil?
	@batch_red = Batch.find params[:transfer][:batch_red] unless params[:transfer][:batch_red].nil?
	@batch_act = Batch.find params[:batch_act]
	unless params[:transfer][:students].nil? and params[:transfer][:batch_cible].nil? and params[:transfer][:batch_red].nil?
		 students = Student.find(params[:transfer][:students])
		 students.each do |s|
			if(!@batch_cible.nil? and !@batch_act.nil? and (@batch_act.course_id == 1 or @batch_act.course_id == 3 or @batch_act.course_id == 5) )
				s.batch_students.create(:batch_id => s.batch.id)
				s.update_attribute(:batch_id, @batch_cible.id)
				s.update_attribute(:has_paid_fees,0)
			elsif(!@batch_cible.nil? and !@batch_act.nil? and @batch_act.course_id != 6)
				batch_prec = Batch.find(:first, :conditions => "course_id = #{@batch_act.course_id-1} and school_field_id = #{@batch_act.school_field_id.to_s} and (year(start_date) = #{@batch_act.get_batch_year})")
				if (!batch_prec.nil?)
					ydecision=YearlyDecision.find(:first, :conditions => "student_id = #{s.id} and school_year = #{@batch_act.get_batch_year.to_s} and batch_ids like '%#{(batch_prec.id.to_s << ',' << @batch_act.id.to_s << ',')}%'")
					if(!ydecision.nil? and ydecision.decision.to_s != "AnneeReserve" and ydecision.decision.to_s != "Exclu" and ydecision.decision.to_s != "Ajourne" and ydecision.decision.to_s != "Reoriente")
						logger.debug '***********************cas du reussit*************************************'
						logger.debug ydecision.decision.to_s
						s.batch_students.create(:batch_id => s.batch.id)
						s.update_attribute(:batch_id, @batch_cible.id)
						s.update_attribute(:has_paid_fees,0)
					elsif(!ydecision.nil? and ydecision.decision.to_s == "AnneeReserve")
						s.batch_students.create(:batch_id => s.batch.id)
						s.update_attribute(:batch_id, @batch_red.id)
						s.update_attribute(:has_paid_fees,0)
					end
				end
			end
		 end
	end

	flash[:notice] = "#{t('flash1')}"
    redirect_to :controller => 'batch_transfers'
  end
=end

def transfer
	exist_res = params[:existe_res]
	existe_red = params[:existe_red]
	@batch_cible = Batch.find params[:transfer][:batch_cible] unless params[:transfer][:batch_cible].nil?
	@batch_red = Batch.find params[:transfer][:batch_red] unless params[:transfer][:batch_red].to_i == 0
	@batch_act = Batch.find params[:batch_act]
	if(exist_res)
		unless params[:transfer_res].nil?
                      if (params[:transfer_res][:students] and params[:transfer][:batch_cible])

app/views/batch_transfers/index.html.erb
<%-# ENIM
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project ENIM - http://www.projectENIM.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
    <%= link_to "#{t('configuration_text')} Académique", configuration_advanced_path %> &nbsp;&raquo;&nbsp;
<%= link_to "#{t('courses_text')}-#{t('home')}", courses_index_path %> &nbsp;&raquo;&nbsp;
<%= link_to t('manage_batch'), courses_manage_batches_path %> &nbsp;&raquo;&nbsp;
<%= t('batch_transfer') %>

  </li>
</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="form-group">
        <h1 class="page-header"><%= t('batch_transfer') %> - <%= t('home') %></h1>
      </div>
    </div><!--/.row-->

      <div class="row">
        <div class="col-md-12 pull-left">
      <% yd=2009
         yf=Date.today.year + 1
     %>  
        
               <select id="school_year" class="form-control">
      <% while yd <= yf 
          if((yd+1 == Date.today.year and Date.today.mon < 8) or (yd == Date.today.year and Date.today.mon > 8))%>
        <option selected value=<%= yd.to_s %>><%= yd.to_s+'/'+(yd+1).to_s %></option>
        <% else %>
          <option value=<%= yd.to_s %>><%= yd.to_s+'/'+(yd+1).to_s %></option>
        <% end %>
      <% 
      yd += 1
      end %>
      </select>

      <%= image_tag("loader.gif",
                   :align => "absmiddle",
                   :border => 0,
                   :id => "loader",
                   :style =>"display: none;" ) %>
  </div>
   </div>
  <div class="row">
    <div class="col-md-12 pull-left">
    <%= select :school_field, :id, @school_fields.map {|u| [u.name.to_s,u.id]},
    {:prompt => "#{t('select_school_field')}"}, :class=>"form-control"%>
    </div>
   </div>

    <div class="row">
      <% unless flash[:notice].nil? %>
        <div class="col-md-12 pull-left">
          <p class="flash-msg"> <%= flash[:notice] %> </p>
        </div>
      <% end %>
      <div class="col-md-12 pull-left">
        <div class="form-group">
          <%= select :courses, :name,
            Course.active.map {|b| [b.course_name+'/'+b.section_name, b.id]},
            {:prompt => "#{t('select_a_course')}"},
            {:onChange => "#{remote_function(:url => {:action => "update_batch"},
        :with => "'course_name='+ value+'&school_field_id='+$('school_field_id').value+'&school_year='+$('school_year').value",
            :before => "Element.show('loader')",
            :success => "Element.hide('loader')"
            )}", :class=>"form-control"} %>
        </div>
      </div>

      <div id="update_batch" style="width:100%" class="col-md-12 pull-left"></div>

      <div class="extender"></div>

    </div>
  </div>
</div>

