config/routes.rb
Rails.application.routes.draw do
  get 'partials/student'
  get 'partials/admin'
  get 'partials/employee'
  get 'configuration/index'
  get 'configuration/settings'
  get 'configuration/advanced'
  get 'configuration/add_weekly_holidays'
  get 'home/index'
  resources :users
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'all', to: 'users#all'
get 'create', to: 'users#create'
get 'index', to: 'users#index'
get 'new' , to: 'users#new'
post '/users/listuser', to: 'users#listuser'
get 'user/profile/:id', to: 'user#profile', as: 'user_profile'


get 'login', to: 'sessions#new', as: 'login'
get 'utilisateurs' , to: 'users#utilisateurs'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'dashboard', to: 'sessions#dashboard'
#get 'new' , to: 'sessions#new'
get 'settings', to: 'configuration#settings'
get 'index', to: 'configuration#index'
get 'advanced', to: 'configuration#advanced'
get 'add_weekly_holidays', to: 'configuration#add_weekly_holidays'
 resources :courses do
    resources :batches
  end
 get 'index' , to: 'courses#index'
 get 'manage_courses', to: 'courses#manage_courses'
  put 'update' , to: 'courses#update'
 get 'edit' , to: 'courses#edit'
 get 'show' , to: 'courses#show'
 get 'new' , to: 'courses#new'
  get 'grouped_batches' , to: 'courses#grouped_batches'
 get 'destroy' , to: 'courses#destroy'
 get 'manage_batches', to: 'courses#manage_batches'
 get 'rechercher_par_filiere' , to: 'courses#rechercher_par_filiere'
 get 'batch_transfers/update_batch', to: 'batch_transfers#update_batch'
get 'grading_levels', to: 'grading_levels#index'
 get 'index', to: 'batch_transfers#index'
 resources :batch_transfers, only: [:index]

  #get 'update' , to: 'courses#update'
 get 'courses/new'
 get 'courses/index'
  #get 'courses/edit'
  #get 'courses/update'
 #get'courses/manage_courses'
 get 'new', to: 'grp_batches#new'
 get 'grp_batches/show_batches/:course_id/:id', to: 'grp_batches#show_batches', as: 'show_batches'
 #delete 'grp_batches/:id', to: 'grp_batches#destroy', as: 'grp_batch'
 delete '/grp_batches/:id', to: 'grp_batches#destroy', as: 'destroy_grp_batch'

 get 'destroy' , to: 'batches#destroy'
  #get 'destroy' , to: 'courses#destroy'
resources :student do
  post 'admission1', on: :collection
end
#resources :manage_courses, only: [:index, :destroy]

  get '/requestdoc_students/index', to: 'requestdoc_students#index'
get 'admission1' , to: 'student#admission1'
get 'profile/:id', to: 'student#profile'
 get 'student/sans_semestre/:id', to: 'student#sans_semestre', as: 'student_sans_semestre'
 get 'student/sans_semestre_sans_rattr/:id', to: 'student#sans_semestre_sans_rattr'
 get 'student/history/:id', to: 'student#history'
 get 'student/student_card/:id', to: 'student#student_card'
 get 'student/gestion_student_card/:id', to: 'student#gestion_student_card'
 
get 'new' , to: 'batches#new'

post 'courses/:course_id/create_batch_group', to: 'courses#create_batch_group', as: 'create_batch_group'


#post '/students', to: 'student#admission1'




 
resources :courses do
  member do
    get 'manage_courses'
    
  end

end
resources :grp_batches do
  collection do
    get 'new/:course_id', to: 'grp_batches#new', as: 'new_grp_batch'
    get 'grouped_batches', to: 'courses#grouped_batches'
  end
end
resources :batch_grps

end

app/models/user.rb
 class User < ApplicationRecord
  has_secure_password
#  validates :email, presence: true, uniqueness: true
#  validates :role, presence: true, on: :create
 enum role: { admin: 0, student: 1, employee: 2 }
# #attr_accessor :role, :admin , :student , :employee


# def before_save
#   logger.debug"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
#     self.salt = random_string(8) if self.salt == nil
#     self.hashed_password = Digest::SHA1.hexdigest(self.salt + self.password) unless self.password.nil?
#     if self.new_record?
#       self.admin, self.student, self.employee = false, false, false
#       self.admin    = true if self.role == 'Admin'
#       self.student  = true if self.role == 'student'
#       self.employee = true if self.role == 'Employee'
#       self.parent = true if self.role == 'Parent'
#     end
#   end

#   def full_name
#     "#{last_name} #{first_name}"
#   end
#   def role_name
#     return "#{t('admin')}" if self.admin?
#     return "#{t('student_text')}" if self.student?
#     return "#{t('employee_text')}" if self.employee?
#     return "#{t('parent')}" if self.parent?
#     return nil
#   end

#   def role_symbols
#     prv = []
#     @privilge_symbols ||= privileges.map { |privilege| prv << privilege.name.underscore.to_sym }

#     if admin?
#       return [:admin] + prv
#     elsif student?
#       return [:student] + prv
#     elsif employee?
#       employee = employee_record
#       unless employee.nil?
#         if employee.subjects.present?
#           prv << :subject_attendance if Configuration.get_config_value('StudentAttendanceType') == 'SubjectWise'
#           prv << :subject_exam
#         end
#         if Batch.active.collect(&:employee_id).include?(employee.id.to_s)
#           prv << :view_results
#         end
#       end
#       return [:employee] + prv
#     elsif parent?
#       return [:parent] + prv
#     else
#       return prv
#     end
#   end


#  private

#   def user_params
#    params.require(:user).permit(:username, :last_name, :first_name,  :email, :password, :password_confirmation, :role, :admin , :student , :employee)
#   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "main" 
  before_action :set_user, only: %i[ show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
 def show
  logger.debug"hohoohh"

  if params[:id] == 'listuser'
    @user = nil
  else
    @user = User.find(params[:id])
  end
end

def dashboard
  @user = current_user
  @config = Configuration.available_modules
  @employee = @user.employee_record if ['employee', 'admin'].include?(@user.role_name.downcase)

  if @user.student?
    @student = Student.find_by(admission_no: @user.username)
    @student = @user.student_record if @student.nil?
    @batch = Student.find_by(user_id: @user.id)&.batch
    @mobility = Mobility.find_by_sql("SELECT * FROM mobilities WHERE school_year = #{batch.get_batch_year.to_i}") if @batch
  end

  if @user.parent?
    @student = Student.find_by(admission_no: @user.username[1..]) if @user.username.present?
  end

  # Other code for dash_news goes here
end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
    def create
  @user = User.new(user_params)
  logger.debug"$$$$$$$"
  logger.debug  @user.inspect
   puts @user.admin
  puts @user.student
  puts @user.employee


  # Set additional attributes based on role
  if params[:role]='admin'
    logger.debug"HHHHHH"
    @user.admin = true
  elsif params[:role]='employee'
    @user.employee = true
    logger.debug"HHHHHH"
  else  
    @user.student = true
    logger.debug"HHHHHH"
  end

  if @user.save
    # User successfully created
    redirect_to dashboard_path
  end
end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
def all
    @users = User.all
    logger.debug"hhhhh"
  end
  



def listuser
  logger.debug"kokokokokok"
  if params[:role] == 'admin'
 @users = User.where(admin: true).order(first_name: :asc)
logger.debug"lllllllllllllllllllll"
    render(:update) do |page|
      render partial: 'users/user'
    end
  elsif params[:role] == 'employee'
    render(:update) do |page|
      render partial:'users/employee_user'
    end
  elsif params[:role] == 'student'
    render(:update) do |page|
     render partial: 'users/student_user'
    end
  elsif params[:role].blank?
    @users = ""
    render(:update) do |page|
     render partial: 'users/user'
    end
  end
end




 def list_employee_user
    emp_dept = params[:dept_id]
    @employee = Employee.find_all_by_employee_department_id(emp_dept, :order =>'first_name ASC')
    @users = @employee.collect { |employee| employee.user}
    @users = @users.sort_by { |e| e.last_name }
    @users.delete(nil)
    render(:update) {|page| page.replace_html 'users', partial: 'users'}
  end
  def list_student_user
    batch = params[:batch_id]
    @student = Student.find_all_by_batch_id(batch, :conditions => { :is_active => true },:order =>'first_name ASC')
    @users = @student.collect { |student| student.user}
    @users = @users.sort_by { |e| e.last_name }
    @users.delete(nil)
    render(:update) {|page| page.replace_html 'users', :partial=> 'users'}
  end

  def list_parent_user
    batch = params[:batch_id]
    @guardian = Guardian.find(:all, :select=>'guardians.*',:joins=>'INNER JOIN students ON students.id = guardians.ward_id', :conditions => 'students.batch_id = ' + batch + ' AND is_active=1',:order =>'first_name ASC')
    users = @guardian.collect { |g| g.user}
    users.compact!
    @users  = users.paginate(:page=>params[:page],:per_page=>20)
    render(:update) {|page| page.replace_html 'users', :partial=> 'users'}
  end


 def dashboard
    @user = current_user
    @config = Configuration.available_modules
    @employee = @user.employee_record if ['employee','admin'].include?(@user.role_name.downcase)
    if @user.student?
      @student = Student.find_by_admission_no(@user.username)
  @student = @user.student_record
      # @batch_year = Student.find_by_user_id(@user.id).batch.get_batch_year


     @batch = Student.find_by_user_id(@user.id).batch 
      @mobility = Mobility.find_by_sql("select * from mobilities where school_year =#{@batch.get_batch_year.to_i}")


    end
    if @user.parent?
      @student = Student.find_by_admission_no(@user.username[1..@user.username.length])
    end
    #    @dash_news = News.find(:all, :limit => 3)
  end


  def search_user_ajax
    unless params[:query].nil? or params[:query].empty? or params[:query] == ' '
      #      if params[:query].length>= 3
      #        @user = User.first_name_or_last_name_or_username_begins_with params[:query].split
      @user = User.find(:all,
        :conditions => "(first_name LIKE \"#{params[:query]}%\"
                       OR last_name LIKE \"#{params[:query]}%\"
                       OR (concat(first_name, \" \", last_name) LIKE \"#{params[:query]}%\")
                       OR username LIKE  \"#{params[:query]}\")",
        :order => "first_name asc") unless params[:query] == ''
      #      else
      #        @user = User.first_name_or_last_name_or_username_equals params[:query].split
      #      end
      #      @user = @user.sort_by { |u1| [u1.role_name,u1.full_name] } unless @user.nil?
    else
      @user = ''
    end
    render :layout => false
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
       if params[:id] == 'listuser'
         @user = nil
         else
    # Find the user based on the ID
    @user = User.find(params[:id])
    end
end
    # Only allow a list of trusted parameters through.
    def user_params
  params.require(:user).permit(:username, :last_name, :first_name,  :email, :password, :password_confirmation,  :admin , :student , :employee , :role)
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_employee_user.html.erb
<div class="form-group col-md-6">

<div class=" "><%#= select :user_type, :type, EmployeeDepartment.active.map {|c| [c.name, c.id]},
    {:prompt => "#{t('select_a_department')}"},
    {:onChange => "#{remote_function(:url => {:action => "list_employee_user"},
    :with => "'dept_id='+value",
        :before => "Element.show('loader')",
        :success => "Element.hide('loader')"
        )}"} %>

</div>
 </div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :role %>
    <%= form.select :role, options_for_select(['admin', 'student', 'employee']) %>
  </div>
  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username%>
  </div>



  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_student_user.html.erb
hhhhhhhhhhhhhhhhhhhhhhhhhhhh

<div class="form-group col-md-6">
  <div class=" ">


    <%= form_tag(users_listuser_path) do %>
  <%= observe_select_field :role,
                           [['Admin', 'admin'], ['Student', 'student'], ['Employee', 'employee']],
                           onchange: "alert('Select field changed!'); this.form.submit();",
                           before: "Element.show('loader')",
                           success: "Element.hide('loader')" %>
<% end %>
    <%#= select_tag 'batch[batch_id]',
                   options_for_select(Batch.active.all.map { |c| [c.full_name, c.id] }),
                   prompt: "#{t('select_a_batch')}",
                   data: {
                     action: "change->user#listStudentUser",
                     controller: "user",
                     target: "loader"
                   } %>
  </div>
</div>

app/views/users/_user.html.erb
<% if @users.nil? or @users.empty? %>
  <div id="user_no_result"><%= t('no_users') %></div>
<% else %>
  <div class="students-table">
    <table class="table table-bordered table-lg table-v2 table-striped" align="center" width="100%" cellpadding="1" cellspacing="1">
      <tr class="tr-head">
        <td>
          <%= t('sl_no') %>
        </td>
        <td>
          <%= t('name') %>
        </td>
        <td>
        <%= t('username') %>
        </td>
        <td>
        
        </td>
      </tr>
      <tr>
        <td>

        </td>
        <td>

        </td>
        <td>

        </td>
        <td>

        </td>
      </tr>
      <% @users.each_with_index do |user,i| %>
        <tr class="tr-<%= cycle('odd', 'even') %>">
          <td class="">
            <%= i+1 %>
          </td>
          <td class="">
      <%=  user.full_name %>
          </td>
          <td class="">
            <%= user.username %>
          </td>
          <td class="">
            <%= link_to "'view_profile'", controller: 'user', action: 'profile', id: user.username  %>
          </td>

        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/users/all.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
      <%= link_to t('manage_users'), utilisateurs_path %> &nbsp;&raquo;&nbsp;
<%= t('all_users') %>

   </li>
</ul>
 <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t('details_about_user') %></h1>
      </div>
    </div><!--/.row-->
    <div class="row">
      <div class="col-md-12 pull-left">
        <% if flash[:notice].present? %>
  <p class="flash-msg"><%= flash[:notice] %></p>
<% end %>

<div class="row">
  <div class="form-group col-md-12 pull-left">
    <div  >
   <%= form_tag(users_listuser_path) do %>
  <%= observe_select_field :role,
                           [['Select', 'select'],['Admin', 'admin'], ['Student', 'student'], ['Employee', 'employee']],
                           before: "Element.show('loader')",
                           success: "Element.hide('loader')" %>
<% end %>


    </div>
    <div id="selectuser"> </div>
  <%#= select :user_type, :type, [["#{t('admin')}","Admin"], ["Intervenant","Employee"],["#{t('student_text')}","Student"],["#{t('parent')}","Parent"]],
  {:prompt => "#{t('select_a_role')}"},
  {:data => { :url => url_for(action: "list_user") },
   :remote => true,
   :before => "Element.show('loader')",
   :success => "Element.hide('loader')" } %>

   <%#= select :user_type, :type, [["Admin"], ["Employee"],["Student"],["Parent"]],
  {:prompt => "select_a_role"
  {:data => { :action => url_for(action: "list_user") },
   :remote => true,
   :before => "Element.show('loader')",
   :success => "Element.hide('loader')" } %>

   <%#= form_tag({ controller: 'users', action: 'list_user' }, method: 'post') do  %>
  <%#= select 'select_a_role', options_for_select([["Admin", "Admin"], ["Student", "Student"], ["Employee", "Employee"], ["Parent", "Parent"]]) %>
  <%#= select :school_field, :id,  options_for_select([["Admin", "Admin"], ["Student", "Student"], ["Employee", "Employee"], ["Parent", "Parent"]]),
               {:prompt => "#{t('select_school_field')}"} , {:class=>"form-control"} %>
  
<%# end %>
<%#= form_tag({ action: 'list_user', method: 'post', enctype: 'multipart/form-data' }, id: 'msform', remote: true) do %>
  <%#= select_tag :user_type, options_for_select([["Admin", "Admin"], ["Student", "Student"], ["Employee", "Employee"], ["Parent", "Parent"]]), prompt: 'select' %>
  
<%# end %>
<%#= link_to t('view_all'), action: :list_user , :user_type=> "Admin" %>


<%#= select_tag :user_type, options_for_select(['Admin', 'Employee', 'Student']), prompt: 'Select User Type', id: 'userTypeSelect' %>



<%#= form_with(model: @user) do |form| %>
<%#= form.select :two, [['admin',1],['employee',2]] %>
<%#= f.submit 'Submit' %>

  <%# end %>




  </div>
</div>
 <div id="student_user" class="form-group col-md-12 pull-left">

          </div>
          <div id="employee_user" class="form-group col-md-12 pull-left">

          </div>
        </div>
        <div class='row'>
          <div id="users" class="col-md-12 pull-left">

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  const select = document.querySelector('#role');

  select.addEventListener('change', function (event) {
    const value = event.target.value;
    var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
       // Typical action to be performed when the document is ready:
       document.getElementById("users").innerHTML = xhttp.responseText;
    }
};
xhttp.open("POST", "/users/listuser?role=" + value , true);
xhttp.setRequestHeader('X-CSRF-Token', document.querySelector('meta[name=csrf-token]').content);
xhttp.send();
  });
</script>


app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/list_user.js.erb
// app/views/users/list_user.js.erb
document.getElementById('users').innerHTML = '<%= j render(@users) %>';
document.getElementById('employee_user').textContent = '';
document.getElementById('student_user').textContent = '';

app/views/users/new.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
  <%= link_to t('manage_users'), utilisateurs_path %> &nbsp;&raquo;&nbsp;
  <%= t('create_user') %>
</li>
</ul> 
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t('make_new_admin_user') %></h1>
      </div>
    </div>
    <div class="row">

      <% unless flash[:notice].nil? %> <div class="col-lg-12"><p class="flash-msg"> <%= flash[:notice] %> </p></div> <% end %>
      <style>
        form{width:100%}
      </style>
      <div class="col-lg-12">
          <div id="necessary-field-notification"><%= t('legend1') %> <span class="necessary-field">*</span> <%= t('legend2') %>  (<%= t('only_admin_user_can_created') %>)</div>
<br>



<%= render "form", user: @user %>



<br>

app/views/users/show.html.erb
<% if @user %>
  <%= render @user %>
<% else %>

<div>
  <%#= link_to "Edit this user", edit_user_path(@user) %> |
  <%#= link_to "Back to users", users_path %>

  <%#= button_to "Destroy this user", @user, method: :delete %>
</div>
 <% end %>

app/views/users/utilisateurs.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
    <%= t('manage_users') %> 
  </li>
</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t('detailed_about_user') %></h1>
      </div>
    </div><!--/.row-->
    <div class="row">
      <div class='col-md-6 pull-left'>
        <div class="panel-default">
          <div class="tabs">
            <ul class="nav nav-tabs">
          <li><%= link_to t('view_all'), action: :all %></li>
              <li><%= link_to t('add_new'), action: :new %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class='col-md-6 pull-left text-right'>
        <div>
          <form name="search-form" id="search-form">
            <%#= image_tag("loader.gif",
              :align => "absmiddle",
              :border => 0,
              :id => "loader",
              :style =>"display: none;" ) %>
            </label>
            <%= text_field_tag "query", params[:query], :autocomplete => 'off', :placeholder =>"#{t('search_user')}",
            :class=>'form-control', :style=>"width: 200px;float: right;" %>
          </form>
        </div>
      </div>

      <div class="col-md-12 pull-left">
        <br><hr><br>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 pull-left">
        <% unless flash[:notice].nil? %> <p class="flash-msg"> <%= flash[:notice] %> </p> <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 pull-left">
        <%#= observe_field 'query', :frequency => 0.5,
        :update => 'user_information',
        :url => { :action => 'search_user_ajax' },
        :before => "Element.show('loader')",
        :success => "Element.hide('loader')",
        :with => 'query' %>
        <script type="text/javascript">
  import { Controller } from "@hotwired/stimulus";

  export default class extends Controller {
    static targets = ["query", "loader", "userInformation"];

    connect() {
      this.queryObserver = new MutationObserver(this.searchUserAjax.bind(this));
      this.queryObserver.observe(this.queryTarget, { childList: true, subtree: true });
    }

    disconnect() {
      this.queryObserver.disconnect();
    }

    searchUserAjax() {
      if (this.queryTarget.value.includes("%")) return;

      this.loaderTarget.style.display = "block";

      const url = this.data.get("url");
      const query = this.queryTarget.value;

      fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: query })
      })
        .then(response => response.text())
        .then(html => {
          this.loaderTarget.style.display = "none";
          this.userInformationTarget.innerHTML = html;
        });
    }
  }
</script>

      <div id="user_information"> </div>
      <div class="extender"> </div>
    </div>
  </div>
</div>
</div>