config/routes.rb
Rails.application.routes.draw do
  get 'partials/student'
  get 'partials/admin'
  get 'partials/employee'
  get 'configuration/index'
  get 'configuration/settings'
  get 'configuration/advanced'
  get 'configuration/add_weekly_holidays'
  get 'home/index'
  resources :users
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'all', to: 'users#all'
get 'create', to: 'users#create'
get 'index', to: 'users#index'
get 'new' , to: 'users#new'
post '/users/listuser', to: 'users#listuser'
get 'user/profile/:id', to: 'user#profile', as: 'user_profile'


get 'login', to: 'sessions#new', as: 'login'
get 'utilisateurs' , to: 'users#utilisateurs'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'dashboard', to: 'sessions#dashboard'
#get 'new' , to: 'sessions#new'
get 'settings', to: 'configuration#settings'
get 'index', to: 'configuration#index'
get 'advanced', to: 'configuration#advanced'
get 'add_weekly_holidays', to: 'configuration#add_weekly_holidays'
 resources :courses do
    resources :batches
  end
 get 'index' , to: 'courses#index'
 get 'manage_courses', to: 'courses#manage_courses'
  put 'update' , to: 'courses#update'
 get 'edit' , to: 'courses#edit'
 get 'show' , to: 'courses#show'
 get 'new' , to: 'courses#new'
  get 'grouped_batches' , to: 'courses#grouped_batches'
 get 'destroy' , to: 'courses#destroy'
 get 'manage_batches', to: 'courses#manage_batches'
 get 'rechercher_par_filiere' , to: 'courses#rechercher_par_filiere'
 get 'batch_transfers/update_batch', to: 'batch_transfers#update_batch'
get 'grading_levels', to: 'grading_levels#index'
 get 'index', to: 'batch_transfers#index'
 resources :batch_transfers, only: [:index]

  #get 'update' , to: 'courses#update'
 get 'courses/new'
 get 'courses/index'
  #get 'courses/edit'
  #get 'courses/update'
 #get'courses/manage_courses'
 get 'new', to: 'grp_batches#new'
 get 'grp_batches/show_batches/:course_id/:id', to: 'grp_batches#show_batches', as: 'show_batches'
 #delete 'grp_batches/:id', to: 'grp_batches#destroy', as: 'grp_batch'
 delete '/grp_batches/:id', to: 'grp_batches#destroy', as: 'destroy_grp_batch'

 get 'destroy' , to: 'batches#destroy'
  #get 'destroy' , to: 'courses#destroy'
resources :student do
  post 'admission1', on: :collection
end
#resources :manage_courses, only: [:index, :destroy]

  get '/requestdoc_students/index', to: 'requestdoc_students#index'
get 'admission1' , to: 'student#admission1'
get 'profile/:id', to: 'student#profile'
 get 'student/sans_semestre/:id', to: 'student#sans_semestre', as: 'student_sans_semestre'
 get 'student/sans_semestre_sans_rattr/:id', to: 'student#sans_semestre_sans_rattr'
 get 'student/history/:id', to: 'student#history'
 get 'student/student_card/:id', to: 'student#student_card'
 get 'student/gestion_student_card/:id', to: 'student#gestion_student_card'
 
get 'new' , to: 'batches#new'

post 'courses/:course_id/create_batch_group', to: 'courses#create_batch_group', as: 'create_batch_group'


#post '/students', to: 'student#admission1'




 
resources :courses do
  member do
    get 'manage_courses'
    
  end

end
resources :grp_batches do
  collection do
    get 'new/:course_id', to: 'grp_batches#new', as: 'new_grp_batch'
    get 'grouped_batches', to: 'courses#grouped_batches'
  end
end
resources :batch_grps

end

app/models/grp_batch.rb
class GrpBatch < ActiveRecord::Base
 

end

app/controllers/grp_batches_controller.rb
class GrpBatchesController < ApplicationController
  layout "main"

	def new 
		@course = Course.find(params[:course_id])
		@grp_batch = GrpBatch.new
		@grp_batches = GrpBatch.where(course_id: params[:course_id])


    end 

    def create
    	 @grp_batch = GrpBatch.new(grp_batch_params)
  @grp_batches = GrpBatch.find_by_course_id(grp_batch_params[:course_id])

      if @grp_batch.save
        redirect_to new_grp_batch_path(course_id: params[:grp_batch][:course_id])

        #render :js=>"window.location='#{new_grp_batch_path(:course_id=>params[:grp_batch][:course_id])}'"
       #redirect_to controller: "grp_batches", action: "new", id: grp_batch_params[:course_id]

      end
    end  

    def index
    end	

    def show_batches
    	 @grp_batch = GrpBatch.find(params[:id])
    	  @grp_batch_batches = GrpBatchBatch.find_all_by_grp_batch_id(@grp_batch.id)
           
          @grp_batch_batch = GrpBatchBatch.find_by_grp_batch_id(@grp_batch.id)
           @bts = []
           @grp_batch_batches.each do |b|
           	@bts << Batch.find(b.batch_id)
           end
           @batches = Batch.find_all_by_course_id(@grp_batch.course_id).select{|e| e.get_batch_year == 2021}
           @batches = @batches - @bts
    	    

    end 
   

    def add_all
        @grp_batch_id = params[:grp_batch_id].to_i
    	#@batch_grp_id=params[:batch_grp_id].to_i
       @batches=params[:add_res][:batches]
      @batches.each do |b|
      	logger.debug "******************************************************************************************"
      	logger.debug @grp_batch_id.to_i
      	logger.debug b.to_i
      	logger.debug "******************************************************************************************"
      	@grp_batch_batch = GrpBatchBatch.new(:grp_batch_id => @grp_batch_id.to_i , :batch_id => b.to_i )
        @grp_batch_batch.save
      
    end

     redirect_to :controller=>"grp_batches", :action=>"show_batches", :id=>@grp_batch_id.to_i
    end	

   def destroy_all
  @batches = params[:destroy_res][:batches]
  @grp_batch_id = params[:grp_batch_id]
  @batches.each do |b|
    logger.debug "***************************************555555555555555555***************************************************"
    logger.debug @grp_batch_id.to_i
    logger.debug b.to_i
    logger.debug "************************************5555555555555555555******************************************************"
    @grp_batch_batch = GrpBatchBatch.find_by(grp_batch_id: @grp_batch_id, batch_id: b.to_i)
    @grp_batch_batch.destroy
  end

  redirect_to grp_batches_show_batches_url(id: @grp_batch_id.to_i)
end

def destroy
  if params[:id].present?
    @grp_batch = GrpBatch.find(params[:id])
    @grp_batch.destroy
    #redirect_to grp_batches_path, notice: 'Batch deleted successfully.'
   #redirect_to contoller: "grp_batches" , action: "new" , id: @grp_batch.id
   redirect_to new_grp_batch_path(course_id: @grp_batch.course_id)
  else
    # Handle the case where params[:id] is nil
    redirect_to new , alert: 'Invalid request.'
  end
end




private

def grp_batch_params
  params.require(:grp_batch).permit(:name, :course_id)
end
end


app/views/grp_batches/create.js.erb
// app/views/grp_batches/create.js.erb
<% if @grp_batch.errors.empty? %>
  // Handle successful form submission
  // Optionally update the view or perform any other actions

  // Example: Close a modal or show a success message
  $('#myModal').modal('hide');
  $('#successMessage').show().text('GrpBatch was successfully created.');
<% else %>
  // Handle form submission with errors
  // Optionally update the view or display error messages

  // Example: Show error messages next to form fields
  <% @grp_batch.errors.full_messages.each do |message| %>
    $('<span>').addClass('error').text('<%= message %>').insertAfter($('#<%= f.object_name %>_<%= f.attribute_name %>').parent());
  <% end %>
<% end %>

app/views/grp_batches/new.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
    <%= link_to t('configuration_text') + " " + "Académique", { controller: "configuration", action: "advanced" } %>
    <%= link_to t('courses_text') + "-" + t('home'), { controller: "courses", action: "index" } %>
    <%= link_to t('manage_course'), manage_courses_path %>
    <%= link_to t('courses_text') + "-" + t('show'), { controller: "courses", action: "show", id: @course.id } %>
    <%= "Groupes de classe" %>
  </li>
</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">Les groupes des classes pour : <%= @course.course_name %></h2>
      </div>
    </div>
    <div class='row'>
      <% unless flash[:notice].nil? %>
        <p class="flash-msg"> <%= flash[:notice] %> </p>
      <% end %>
      <%= form_with model: @grp_batch, url: { controller: 'grp_batches', action: 'create' }, remote: true do |f| %>
        <div class="box">
          <%#= f.error_messages %>
          <%= f.hidden_field :course_id, value: @course.id %>
          <div class="form-group col-md-12 pull-left pull-left">
            <label class="control-label" for="user_username"><%= t('name') %></label>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <br>
          <div>
            <%= submit_tag ('Enregistrer') %>
          </div>
      <% end %>
      <br><br>
      <div id='listelg'>
        <table id="listing" width="100%" class="table table-bordered table-lg table-v2 table-striped fixed_headers">
          <% unless @grp_batches.blank? %>
            <tr class="tr-head">
              <td>Nom</td>
              <td>Niveau</td>
              <td></td>
            </tr>
            <tr class="tr-blank"></tr>
            <% @grp_batches.each do |lg| %>
              <tr class="tr-<%= cycle('odd', 'even') %>">
                <td>
                  <%= link_to lg.name, show_batches_path(course_id: lg.course_id, id: lg.id) %>

                </td>
                <td><%= Course.find(lg.course_id).course_name %></td>
                <td><%#= button_to new_grp_batch_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <%= button_to "Delete Text",  {contoller: "grp_batches" , action: "destroy", id: lg.id} ,  method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>

                <%#= button_to course_path(course), method: :delete, data: { confirm: 'Are you sure?' } do %>

<%# end %>

              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div

app/views/grp_batches/show_batches.html.erb
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="."><%= "Liste des classes du groupe"  %></a>
  </li>
</ul>


<div class="content-i" >
   <div class="content-box">
      <div class="row">
         <div class="col-lg-12">
            <h2 class="page-header"></h2>
         </div>
      </div>

      <div class='row'>
         <% unless flash[:notice].nil? %>
         <p class="flash-msg"> <%= flash[:notice] %> </p>
         <% end %>





  

 

<div class="content-i">

    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><%= @grp_batch.name %>  </h3>

        <h4 class="page-header"><%= "Liste des classes du groupe"  %></h4>
      </div>
    </div>
<% unless @grp_batch_batches.blank? %>
<% form_for :show_det, :url => { :controller => 'grp_batches', :action => 'destroy_all', :grp_batch_id => @grp_batch.id 
} do |f| %>


    <table id="listing" width="100%" class="table table-bordered table-lg table-v2 table-striped fixed_headers">   
      <tr class="tr-head">
                   <td>classe</td>
                   <td>
                    <%= link_to_function t('all'), "$$('input.rightt').each(function(checkbox) { checkbox.checked = true; });" %>,
                    <%= link_to_function t('none'), "$$('input.rightt').each(function(checkbox) { checkbox.checked = false; });" %>
                   </td>
               </tr>
               <tr></tr>
               <% @grp_batch_batches.each do |lgs|
  
                           batch= Batch.find(lgs.batch_id)
               %>
               <tr class="tr-<%= cycle('odd', 'even') %>">
                    <td class="col-2"><%=  batch.name  %></td>
                    <td class="col-2"><%= check_box_tag 'destroy_res[batches][]', batch.id, false,:class=>"rightt" %></td>
               </tr>
               <% end %>

    </table>

    <%= submit_tag "", :value => "► #{t('delete')}", :class => "btn btn-primary" %>
<% end %>
<% else %>
<h4 class="page-header">Aucune classe  n'est affecté à ce groupe, ajouter parmi la liste dessous!</h4>
<% end %>
</div>
</div>
<br><br>
  <label >
    <%= image_tag("loader.gif",:align => "absmiddle",:border => 0,:id => "loader", :style =>"display: none;" ) %>
  </label>

    <div id="students_list">
    <% form_for :show_det, :url => { :controller => 'grp_batches', :action => 'add_all',
     :grp_batch_id => @grp_batch.id } do |f| %>
    <%#= f.hidden_field :batch_id, :value => @batch_group.batch_id %>
    <div class="content-i">
    <div class="content-box">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header">Ajouter d'autre classe</h3>
          </div>
        </div>

        <table id="listing" width="100%" class="table table-bordered table-lg table-v2 table-striped fixed_headers">   
                <% unless  @batches.blank? %>
          <tr class="tr-head">
                      
                       <td>classe</td>
                       <td>
                        <%= link_to_function t('all'), "$$('input.righttt').each(function(checkbox) { checkbox.checked = true; });" %>,
                        <%= link_to_function t('none'), "$$('input.righttt').each(function(checkbox) { checkbox.checked = false; });" %>
                       </td>
                   </tr>
                   <tr></tr>
                   <% @batches.each do |batch|
                               batch=Batch.find(batch.id)
                   %>
                   <tr class="tr-<%= cycle('odd', 'even') %>">
                       
                        <td class="col-2"><%= batch.name %></td>
                        <td class="col-2"><%= check_box_tag 'add_res[batches][]', batch.id, false,:class=>"righttt" %></td>
                   </tr>
                   <% end %>
                <% end %>
        </table>

        <%= submit_tag "", :value => "► #{t('add')}", :class => "btn btn-primary" %>
    </div>
    </div>
    <% end %>
   </div>
