config/routes.rb
Rails.application.routes.draw do
  get 'partials/student'
  get 'partials/admin'
  get 'partials/employee'
  get 'configuration/index'
  get 'configuration/settings'
  get 'configuration/advanced'
  get 'configuration/add_weekly_holidays'
  get 'home/index'
  resources :users
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'all', to: 'users#all'
get 'create', to: 'users#create'
get 'index', to: 'users#index'
get 'new' , to: 'users#new'
post '/users/listuser', to: 'users#listuser'
get 'user/profile/:id', to: 'user#profile', as: 'user_profile'


get 'login', to: 'sessions#new', as: 'login'
get 'utilisateurs' , to: 'users#utilisateurs'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'dashboard', to: 'sessions#dashboard'
#get 'new' , to: 'sessions#new'
get 'settings', to: 'configuration#settings'
get 'index', to: 'configuration#index'
get 'advanced', to: 'configuration#advanced'
get 'add_weekly_holidays', to: 'configuration#add_weekly_holidays'
 resources :courses do
    resources :batches
  end
 get 'index' , to: 'courses#index'
 get 'manage_courses', to: 'courses#manage_courses'
  put 'update' , to: 'courses#update'
 get 'edit' , to: 'courses#edit'
 get 'show' , to: 'courses#show'
 get 'new' , to: 'courses#new'
  get 'grouped_batches' , to: 'courses#grouped_batches'
 get 'destroy' , to: 'courses#destroy'
 get 'manage_batches', to: 'courses#manage_batches'
 get 'rechercher_par_filiere' , to: 'courses#rechercher_par_filiere'
 get 'batch_transfers/update_batch', to: 'batch_transfers#update_batch'
get 'grading_levels', to: 'grading_levels#index'
 get 'index', to: 'batch_transfers#index'
 resources :batch_transfers, only: [:index]

  #get 'update' , to: 'courses#update'
 get 'courses/new'
 get 'courses/index'
  #get 'courses/edit'
  #get 'courses/update'
 #get'courses/manage_courses'
 get 'new', to: 'grp_batches#new'
 get 'grp_batches/show_batches/:course_id/:id', to: 'grp_batches#show_batches', as: 'show_batches'
 #delete 'grp_batches/:id', to: 'grp_batches#destroy', as: 'grp_batch'
 delete '/grp_batches/:id', to: 'grp_batches#destroy', as: 'destroy_grp_batch'

 get 'destroy' , to: 'batches#destroy'
  #get 'destroy' , to: 'courses#destroy'
resources :student do
  post 'admission1', on: :collection
end
#resources :manage_courses, only: [:index, :destroy]

  get '/requestdoc_students/index', to: 'requestdoc_students#index'
get 'admission1' , to: 'student#admission1'
get 'profile/:id', to: 'student#profile'
 get 'student/sans_semestre/:id', to: 'student#sans_semestre', as: 'student_sans_semestre'
 get 'student/sans_semestre_sans_rattr/:id', to: 'student#sans_semestre_sans_rattr'
 get 'student/history/:id', to: 'student#history'
 get 'student/student_card/:id', to: 'student#student_card'
 get 'student/gestion_student_card/:id', to: 'student#gestion_student_card'
 
get 'new' , to: 'batches#new'

post 'courses/:course_id/create_batch_group', to: 'courses#create_batch_group', as: 'create_batch_group'


#post '/students', to: 'student#admission1'




 
resources :courses do
  member do
    get 'manage_courses'
    
  end

end
resources :grp_batches do
  collection do
    get 'new/:course_id', to: 'grp_batches#new', as: 'new_grp_batch'
    get 'grouped_batches', to: 'courses#grouped_batches'
  end
end
resources :batch_grps

end

app/models/batch_group.rb
#EMI
#Copyright 2011 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project EMI - http://www.projectEMI.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
class BatchGroup < ActiveRecord::Base
  belongs_to :course
  has_many :grouped_batches, :dependent=>:destroy
  has_many :batches, :through=>:grouped_batches

  validates_presence_of :name, :course_id

  def has_active_batches
    self.batches.each do|b|
      return true if (b.is_active and !b.is_deleted)
    end
    return false
  end

end

app/controllers/courses_controller.rb
#FEDENA
#Copyright 2011 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project FEDENA - http://www.projectFEDENA.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class CoursesController < ApplicationController
  layout "main"
  #before_action :login_required
  before_action :find_course, :only => [:show, :edit, :update, :destroy]
  #filter_access_to :all
  #has_many :batches

  def index
    logger.debug"pppppppp"
    @courses = Course.active
  end
 def importsubjects
   @batches = Batch.all
   Rails.logger.info "KOMPL 50"


    filename="#{RAILS_ROOT}/public/uploads/File/FSO-Wail.csv"
    require 'faster_csv'
  Rails.logger.info
  @sub = 0;
    @n_sub = 0;

@ct = 0;
   FasterCSV.foreach(filename,  :col_sep =>',', :row_sep =>:auto) do |row|
    @ct = @ct + 1
    if(@ct>1)
        if row[6].include? "/"
      subject = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6].split("/")[0]])
      subject2 = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6].split("/")[1]])

    else
      subject = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6]])

    end
  if row[6].include? ","
      subject = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6].split(",")[0]])
      subject2 = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6].split(",")[1]])

    else
      subject = Subject.find(:first,:conditions => ["(name LIKE ?)",row[6]])

    end
      if row[5] != nil
      if row[5].include? "/"
        employee = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5].split("/")[0],row[5].split("/")[0],row[5].split("/")[0],row[5].split("/")[0]])
        employee2 = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5].split("/")[1],row[5].split("/")[1],row[5].split("/")[1],row[5].split("/")[1]])
      #  employee = Employee.find_by_last_name( row[5].split("/")[0] )

else
  employee = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5],row[5],row[5],row[5]])

  #employee = Employee.find_by_last_name( row[5])

end
 if row[5].include? " "
        employee = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5].split(" ")[0],row[5].split(" ")[0],row[5].split(" ")[0],row[5].split(" ")[0]])
        employee2 = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5].split(" ")[1],row[5].split(" ")[1],row[5].split(" ")[1],row[5].split(" ")[1]])
      #  employee = Employee.find_by_last_name( row[5].split("/")[0] )

else
  employee = Employee.find(:first,:conditions => ["(first_name LIKE ? OR middle_name LIKE ? OR last_name LIKE ? OR employee_number LIKE ?)",row[5],row[5],row[5],row[5]])

  #employee = Employee.find_by_last_name( row[5])

end
end
if(subject!=nil)
  @sub = @sub + 1
      Rails.logger.info @sub


else
 @n_sub = @n_sub + 1
      Rails.logger.info @n_sub
end
 if(employee != nil && subject!=nil )
      if row[5].include? "/"
        if(employee2 != nil)
        es = EmployeesSubject.new(:employee_id => employee2.id,:subject_id => subject.id)
      es.save
        Rails.logger.info  employee2.first_name + employee2.last_name
       Rails.logger.info subject.name
     end
      end
      if row[6].include? "/"
        if(subject2 != nil)
        es = EmployeesSubject.new(:employee_id => employee2.id,:subject_id => subject2.id)
      es.save
      #  Rails.logger.info  employee2.first_name + employee2.last_name
       Rails.logger.info subject2.name
     end
      end
      es = EmployeesSubject.new(:employee_id => employee.id,:subject_id => subject.id)
    es.save
     Rails.logger.info  employee.first_name + employee.last_name
    Rails.logger.info subject.name
   end
  
    if(employee == nil && subject != nil )
      Rails.logger.info "************//////*************//////***********"
     empl = Employee.new( :employee_category_id=>2, :employee_number=>row[5], :joining_date=>"2018-02-02", :first_name=>row[5], :middle_name=>"", :last_name=> row[5], :gender=>true, :job_title=> "", :employee_position_id=> 2, :employee_department_id=> 4, :reporting_manager_id => nil, :employee_grade_id=>4, :qualification=> "",:experience_detail=> "", :experience_year=> nil,:experience_month=>nil, :status=>true,:status_description=>nil, :date_of_birth=>"2008-02-02",:marital_status=> "single",:children_count=> nil, :father_name=> "", :mother_name=> "", :husband_name=> "", :blood_group=> "Inconnu", :nationality_id=>120, :home_address_line1=> nil,:home_address_line2=> nil, :home_city=>nil, :home_state=>nil, :home_country_id=>nil, :home_pin_code=> nil, :office_address_line1=>nil, :office_address_line2=> nil, :office_city=>nil, :office_state=>nil, :office_country_id=>nil, :office_pin_code=>nil, :office_phone1=> nil, :office_phone2=>nil, :mobile_phone=>nil, :home_phone=>nil,:email=> "test.test@insea.ac.ma", :fax=> nil, :photo_file_name=> nil, :photo_content_type=> nil, :photo_data=> nil, :photo_file_size=> nil, :user_id=> nil).save

#empl = Employee.new(:last_name => row[5] ,:first_name => row[5])
#empl.save
      es = EmployeesSubject.new(:employee_id => empl.id,:subject_id => subject.id)

    end

  if(row[5] != nil)
    if(row[5].include? "all")
    	      

    	if(subject.id != nil)
Employee.all.each do |em|

	es = EmployeesSubject.new(:employee_id => em.id,:subject_id => subject.id)
	es.save
end
end
end
 if(row[5].include? "dss")
    	      

    	if(subject.id != nil)
Employee.all.each do |em|

	es = EmployeesSubject.new(:employee_id => em.id,:subject_id => subject.id)
	es.save
end
end
end
end
end
   end
   #redirect_to :back
  end

  def new
    @course = Course.new
    @grade_types=Course.grading_types_as_options
    @school_fields=SchoolField.all
#    gpa = Configuration.find_by_config_key("GPA").config_value
#    if gpa == "1"
#      @grade_types << "GPA"
#    end
#    cwa = Configuration.find_by_config_key("CWA").config_value
#    if cwa == "1"
#      @grade_types << "CWA"
#    end
  end


  def manage_course
    @courses= Course.all
   
  end

  def manage_batches

  end
  def rechercher_par_filiere

    @school_fields = SchoolField.find(:all,  :order => "name")
    
  end
  def show_classes
    @school_field_id=params[:filiere_id]
    @school_year=params[:school_year]
    logger.debug"******************#{params[:filiere_id]}***********************"
    logger.debug"******************#{@school_field_id}***********************"
    @batches = Batch.find_all_by_school_field_id(@school_field_id).reject { |t| t.get_batch_year != @school_year.to_i }
     logger.debug"************************************************************** "
      logger.debug @batches.inspect
       render(:update) do|page|
        page.replace_html "show_classes", :partial=>"show_classe"
        
      end
  end

  def grouped_batches
  @course = Course.find(params[:id])
  @batch_groups = @course.batch_groups
  @batches = @course.batches.where(is_active: true, is_deleted: false)
                            .left_outer_joins(:grouped_batches)
                            .where(grouped_batches: { batch_id: nil })
  @batch_group = BatchGroup.new
end

  def create_batch_group
    @batch_group = BatchGroup.new
    @batch_group.name= params[:name]
    @course = Course.find(params[:course_id])
    @batch_group.course_id = @course.id
    #@batch_group.save
    if ! @batch_group.save
      error_messages = @batch_group.errors.full_messages.join(", ")
      Rails.logger.error("Failed to save student. Errors: #{error_messages}")
    end
    @error=false

    if params[:batch_ids].blank?
      @error=true
    end
    logger.debug"gggggggzlekggggggggg"
    if @batch_group.valid? and @error==false
      @batch_group.save
      batches = params[:batch_ids]
      batches.each do|batch|
        GroupedBatch.create(:batch_group_id=>@batch_group.id,:batch_id=>batch)
         logger.debug"gggggggg--------------gggggggg"
      end
      @batch_group = BatchGroup.new
      @batch_groups = @course.batch_groups
      @batches = @course.active_batches.reject{|b| GroupedBatch.exists?(:batch_id=>b.id)}
      render(:update) do|page|
        page.replace_html "category-list", :partial=>"batch_groups"
        page.replace_html 'flash', :text=>'<p class="flash-msg"> Batch Group created successfully. </p>'
        page.replace_html 'errors', :partial=>"form_errors"
        page.replace_html 'class_form', :partial=>"batch_group_form"
      end
      logger.debug"gggggggg-------666666666-------gggggggg"
    else
      if params[:batch_ids].blank?
        @batch_group.errors.add_to_base "Atleast one batch must be selected."
      else
        abort @batch_group.valid?
      end
    end
  end

  def edit_batch_group
    @batch_group = BatchGroup.find(params[:id])
    @course = @batch_group.course
    @assigned_batches = @course.active_batches.reject{|b| (!GroupedBatch.exists?(:batch_id=>b.id,:batch_group_id=>@batch_group.id))}

app/views/courses/_batch_groups.html.erb
<%-# EMI
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project EMI - http://www.projectEMI.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<ul class="category-list">
  <% unless @batch_groups.empty? %>
    <li class="heading">Grouped Batches</li>
    <% @batch_groups.each  do |batch_group| %>
      <li class="list<%=cycle('odd', 'even')%>">
        <div class="category-name"><%= batch_group.name %></div>
        <div class="category-name"><% batch_group.grouped_batches.each do|b| %>
            <div class="category-name"><%= b.batch.name %></div>
          <% end %></div>
        <div class="category-edit"><%= link_to_remote "#{t('edit_text')}", :url=>{:controller=>"courses",:action=>"edit_batch_group", :id=>batch_group.id}  if permitted_to? :edit_batch_group, :courses %></div><div class="category-delete">   <%= link_to_remote "Delete", :url=>{:controller=>"courses",:action=>"delete_batch_group", :id=>batch_group.id}, :confirm=>"Are you sure?" if permitted_to? :delete_batch_group, :courses %></div>
      </li>
    <% end %>
  <% else %>
    <p class="flash-msg">No Grouped Batches found.</p>
  <% end %>
</ul>


app/views/courses/_update_batches.html.erb
<%-# ENIM
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project ENIM - http://www.projectENIM.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<h3><%= t('active_batches') %></h3>

<table class="table table-bordered table-lg table-v2 table-striped ">
  <% @batch.each do |batch| %>
    <tr>
      <td>
        <%= link_to batch.full_name, [batch.course, batch] %>
      </td>
    </tr>
  <% end %>
</table>

app/views/courses/manage_batches.html.erb
<%-# ENIM
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project ENIM - http://www.projectENIM.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
  
 <li class="breadcrumb-item">
  <%= link_to "configuration_text Académique", configuration_advanced_path %> &nbsp;&raquo;&nbsp;
  <%= link_to ('courses_text home'), { controller: 'courses', action:'index' } %> &nbsp;&raquo;&nbsp;
  <%= t('manage_batch') %>
</li>

</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= ('Niveaux') %> - <%= ('Gérer les classes') %></h1>
      </div>
    </div><!--/.row-->
    <div class="row">
      <div class="col-md-12">
        <div class="panel-default">
          <div class="tabs">
            <ul class="nav nav-tabs">
           
                <li><%= link_to ('Systeme des appréciations') , grading_levels_path %></li>
              
          
              <li><%= link_to ('Transfert de Classe'), batch_transfers_path %></li>

            </ul>
          </div>
        </div>
        <hr>
      </div>
    </div>
    <div class="row">
      <% unless flash[:notice].nil? %>
        <div class="col-md-12 pull-left">
          <p class="flash-msg"> <%= flash[:notice] %> </p>
        </div>
      <% end %>
      <div class="col-md-12 pull-left">
        <div class="form-group">
          <label class="control-label"><%= ('Selectionner un niveau') %></label>
         <%= select_tag :course_name, options_for_select(Course.active.map { |b| [b.course_name + " " + b.section_name, b.id] }, 
          prompt: ('Selectionner un niveau')),
          onchange: "Rails.ajax({url: '#{batch_transfers_update_batch_path}', type: 'GET', data: { course_name: this.value }, beforeSend: function() { $('#loader').show(); }, success: function() { $('#loader').hide(); }});",

           class: 'form-control'
%>
        </div>
        <%#= image_tag("loader.gif",:align => "absmiddle",:border => 0,:id => "loader", :style =>"display: none;" ) %>

      </div>
      <div id="update_batch" class="col-md-12 pull-left" style="width:100%" ></div>
      <div class="extender"></div>
    </div>
  </div>
</div>

app/views/courses/manage_courses.html.erb
<%-# ENIM
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project ENIM - http://www.projectENIM.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
   <li class="breadcrumb-item">
    <%= link_to t('configuration_text')+" "+"Académique", { controller: 'configuration', action:'advanced' }  %> 
    <%= link_to t('courses_text')+"-"+ t('home') , { controller: "courses", action: "index" }  %> 
    <%= t('manage_course') %>
  </li>
</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t('Niveaux') %> - <%= t('Gérer les niveaux') %></h1>
      </div>
    </div><!--/.row-->
    <div class="row">
      <div class="col-md-12 pull-left">
        <div class="panel-default">
          <div class="tabs">
            <ul class="nav nav-tabs">
              <li><%= link_to "nouveau", new_course_path %> </li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
    </div>


    <div class="row">

      <% unless flash[:notice].nil? %>
        <div class="col-md-12 pull-left">
          <p class="flash-msg"> <%= flash[:notice] %> </p>
        </div>
      <% end %>


      <% unless flash[:warn_notice].nil? %>
        <div class="col-md-12 pull-left">
          <div id="errorExplanation" class="errorExplanation"><%= flash[:warn_notice] %> </div>
        </div>
      <% end %>
      <div class="col-md-12 pull-left">
        <table class="table table-bordered table-lg table-v2 table-striped ">
          <tr>
            <th>
              <%= t('Niveaux') %>
            </th>
            <th></th>
            <th></th>
          </tr>
          <% Course.all.each do |course| %>
            <tr>
              <td>
                <%#= link_to course.full_name, course_path(course) %>
                 <%= link_to course.full_name, {controller: "courses" , action: "show" , id: course.id} %>
              </td>
              <td style="width:100px">
                <%= link_to "Modifier", edit_course_path(course), if: can?(:update, :courses) %>

              </td>
              <td style="width:100px">
               <%#= link_to 'delete_text', course_path(course), method: :delete, data: { confirm: 'Are you sure?' }, if: can?(:destroy, :courses) %>
<%#= link_to 'delete_text', method: :delete, data: { confirm: 'Are you sure?' } %>
<%= button_to course_path(course), method: :delete, data: { confirm: 'Are you sure?' } do %>
    Delete Text 
<% end %>
<%#= button_to "Delete",  course, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{course.id}?" %></td>
<td><%#= link_to "Delete", course_path(course), method: :delete %></td>

              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="extender"></div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<%-# ENIM
#Copyright 2010 Cactus IT Technologies Private Limited
#
#This product includes software developed at
#Project ENIM - http://www.projectENIM.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">
      <em class="fa fa-home"></em>
    </a>
  </li>
 <li class="breadcrumb-item">
    <%= link_to t('configuration_text')+" "+"Académique", { controller:  "configuration", action: "advanced" }  %> &nbsp;
      &raquo;&nbsp;
    <%= link_to t('courses_text')+"-"+ t('home'), { controller: "courses", action: "index" }  %> &nbsp;&raquo;&nbsp;
    <%= link_to t('manage_course'), manage_courses_path %> &nbsp;&raquo;&nbsp;
    <%= t('courses_text') %> - <%= t('show') %>
  </li> 


</ul>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t('Niveaux') %> - <%= t('Montrer') %></h1>
      </div>
    </div><!--/.row-->

    <div class="row">
      <div class="col-md-12 pull-left">
        <div class="panel-default">
          <div class="tabs">
            <ul class="nav nav-tabs">
              <li><%= link_to "Groupes des classes" , {controller: "grp_batches", action: "new" , course_id: @course.id} %> </li>
              <li><%= link_to ('Nouveaux'), new_course_batch_path(@course) %> </li>
              <li><%= link_to "Group Batches", {controller: "courses", action: "grouped_batches", id: @course.id} %> </li>
              <% if can?(:edit, :course) %>
                <li><%= link_to "#{t('edit_text')}", edit_course_path(@course) , if: can?(:edit, :course) %></li>
              <%  end %>
              <%  if can?(:destroy, :course)%>
                <li><%= link_to("#{t('delete_text')}", course_path(@course), method: 'delete', confirm: "#{t('delete_confirm_msg')}") %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <hr>
      </div>
    </div>
    <div class="row">
      <% unless flash[:notice].nil? %>
        <div class="col-md-12 pull-left">
          <p class="flash-msg"> <%= flash[:notice] %> </p>
        </div>
      <% end %>


      <div class="col-md-12 pull-left">
        <table class="table table-bordered table-lg table-v2 table-striped ">
          <% @batch.each do |batch| %>
            <tr>
              <td>
                <%= link_to batch.full_name, course_path(@course, batch) %>

              </td>
              <td style="width:100px">
                <%= link_to ('Modifier'), edit_course_batch_path(@course, batch) ,if: can?(:edit, :batches )%>
              </td>
              <td style="width:100px">
                
      
  <%= link_to ('Supprimer') ,{controller: 'batches', action: 'destroy', id:  batch.id}  %>

              </td>
              <td style="width:100px">
                <%= link_to "Sous-Groupes de classe",{ controller: 'batch_grps', action: 'new', id:  batch} %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
        <div class="extender"></div>
    </div>
  </div>
</div>